disabled_rules:
  - trailing_whitespace

excluded:
  - Pods
  - Apple_Weather_App/AppDelegate.swift
  - Apple_Weather_App/SceneDelegate.swift

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - let_var_whitespace
  - operator_usage_whitespace
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces

line_length:
  warning: 250
  error: 400
  
identifier_name:
  min_length: 2
